
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Providers } from './Providers';
import Sidebar from './components/SideBar';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Task Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  return (
    <Providers >
      <html lang="en">
        <body className={inter.className}>
          <div className="flex h-screen">

            <Sidebar/>
            <div className="flex-1 p-8">
            {children}
            </div>
          </div>
        </body>
      </html>
    </Providers>
  )
}
